# Dockerfile.client
FROM node:16-alpine

WORKDIR /app

COPY ./client/package.json .
COPY ./client/package-lock.json .
RUN npm install

COPY ./client .

# Expose the port used by the development server
EXPOSE 3000

CMD ["npm", "start"]
