version: "3"
services:
  client:
    image: client_image  # Image built by the frontend_container role
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    image: server_image  # Image built by the backend_container role
    ports:
      - "4000:4000"
    depends_on:
      - database 

  database:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
