---
- name: Configuring ecommerce website on vm
  hosts: [ecommerce_server]
  become: true  # If you need root/sudo privileges 
  vars:
    repository_url: "https://github.com/victorkimanthi/yolo.git"
    vm_clone_path: "/devops3"  # The path where you want to clone the repository

  tasks:
    # - name: Create directory
    #   file:
    #     path: /devops3  
    #     state: directory
    #     mode: "0755"  # Set appropriate permissions if needed

    - name: Clone the GitHub repository
      git:
        repo: "{{ repository_url }}"
        dest: "{{ vm_clone_path }}"

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes   

    - name: Copy Dockerfile for client
      copy:
        src: /Dockerfile.client
        dest: /Dockerfile.client

    - name: Copy Dockerfile for server
      copy:
        src: /Dockerfile.server
        dest: /Dockerfile.server 
